#169834714 Setting up tests for iFind-Frontend
alainmateso/iFind-frontend pull request #3
Opened 2019-11-19 11:16 UTC by ngireric123

#### What does this PR do?

#### Description of Task to be completed?

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?

#### Screenshots (if appropriate)

#### Questions:

2019-11-19 11:32 UTC, Cheza-Dzabala requested changes
Hi Eric, could you add a dummy component and test it to show that it works?

2019-11-19 11:36 UTC, Cheza-Dzabala commented on src/setupTests.js
> +    disableLifecycleMethods: true
Why this disableLifeCycleMethods?

2019-11-19 17:05 UTC, Cheza-Dzabala approved these changes

2019-11-20 08:11 UTC, alainmateso approved these changes

2019-11-20 08:12 UTC, merged